

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - ./backend/.env
    
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - node_modules_backend:/app/node_modules
      - ${HOME}/Music:/library

volumes:
  node_modules_frontend: {}
  node_modules_backend: {}
