

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ${HOME}/Music:/app/library

volumes:
  node_modules_frontend: {}

