FROM denoland/deno:alpine-2.9.0





RUN apk add ffmpeg rsgain
WORKDIR /app
COPY . .


ENV FORCE_COLOR=1

WORKDIR /app

RUN deno cache --node-modules-dir=auto src/index.ts


EXPOSE 3000

CMD ["task", "dev"]
